// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace comictoolx {
	
	
	// Should subclass MonoMac.AppKit.NSResponder
	[MonoMac.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("closeComic:")]
		partial void closeComic (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("nextPage:")]
		partial void nextPage (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("openComic:")]
		partial void openComic (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("previousPage:")]
		partial void previousPage (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("saveCurrentPage:")]
		partial void saveCurrentPage (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("zoomActual:")]
		partial void zoomActual (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("zoomFit:")]
		partial void zoomFit (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("zoomIn:")]
		partial void zoomIn (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("zoomOut:")]
		partial void zoomOut (MonoMac.AppKit.NSMenuItem sender);
}
}
