// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace comictoolx {
	
	
	// Should subclass MonoMac.AppKit.NSView
	[MonoMac.Foundation.Register("IKImageView")]
	public partial class IKImageView {
	}
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.ImageKit.IKImageView __mt_imageView;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("segmentedClicked:")]
		partial void segmentedClicked (MonoMac.AppKit.NSSegmentedControl sender);

		[MonoMac.Foundation.Export("zoomSliderChanged:")]
		partial void zoomSliderChanged (MonoMac.AppKit.NSSlider sender);

		[MonoMac.Foundation.Connect("imageView")]
		private global::MonoMac.ImageKit.IKImageView imageView {
			get {
				this.__mt_imageView = ((global::MonoMac.ImageKit.IKImageView)(this.GetNativeField("imageView")));
				return this.__mt_imageView;
			}
			set {
				this.__mt_imageView = value;
				this.SetNativeField("imageView", value);
			}
		}
	}
}
